/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Voice */
        post: operations["enroll_voice_voices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices/{voice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Forget Voice
         * @description 明示的に忘れさせる（次の子に交代するとき）。参照音声のファイルも消える。
         */
        delete: operations["forget_voice_voices__voice_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description キャンセルを要求する。走っている1行は最後まで走り、その先が止まる。
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Artifact
         * @description クライアントが書き出した動画を預かる（QRコードで別端末に渡す用）。
         *
         *     サーバー側レンダリングが使える環境では通らない経路。
         *     `canRender=false`（フォントが無い等）のときのフォールバック。
         */
        post: operations["upload_artifact_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Video */
        post: operations["render_video_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops */
        get: operations["ops_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup
         * @description イベント後の後片付け。声も生成物もまとめて消す。
         */
        post: operations["cleanup_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Artifactid */
            artifactId: string;
            /** Expiressec */
            expiresSec: number;
        };
        /** AuthDTO */
        AuthDTO: {
            /** Tokenrequired */
            tokenRequired: boolean;
        };
        /** Body_enroll_voice_voices_post */
        Body_enroll_voice_voices_post: {
            /** Audio */
            audio: string;
            /**
             * Reference Text
             * @default
             */
            reference_text: string;
        };
        /** Body_upload_artifact_artifacts_post */
        Body_upload_artifact_artifacts_post: {
            /** Video */
            video: string;
        };
        /** CancelResponse */
        CancelResponse: {
            /** Cancelled */
            cancelled: boolean;
        };
        /** CleanupResponse */
        CleanupResponse: {
            /** Voices */
            voices: number;
            /** Artifacts */
            artifacts: number;
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /** Voiceid */
            voiceId: string;
            /** Lines */
            lines: string[];
        };
        /**
         * ErrorResponse
         * @description FastAPI の HTTPException が返す形。
         *
         *     注意: 422（バリデーションエラー）だけは FastAPI が `HTTPValidationError`
         *     として自前で定義しており、`detail` が **配列** になる。ここで上書きすると
         *     契約が嘘になるので、422 は宣言しない（schemathesis に指摘されて気づいた）。
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /health — フロントの接続先選びが最初に見る。
         */
        HealthResponse: {
            /**
             * Status
             * @description "ok" か "warming"。warming の間は割り当てない
             */
            status: string;
            /** Version */
            version: string;
            /** Serverid */
            serverId: string;
            /** Color */
            color: string;
            /** Label */
            label: string;
            /**
             * Ttsbackend
             * @description 設定値（こう動かしたい）
             */
            ttsBackend: string;
            /**
             * Ttseffective
             * @description 実際に動いているもの。dummy ならフォールバック中
             */
            ttsEffective: string;
            /**
             * Ttsfallback
             * @description dummy に落ちた理由。正常なら null
             */
            ttsFallback: string | null;
            /** Warmuperror */
            warmupError: string | null;
            /**
             * Canrender
             * @description サーバー側で動画を作れるか
             */
            canRender: boolean;
            /**
             * Queuedepth
             * @description 未処理の行数
             */
            queueDepth: number;
            /** Activejobs */
            activeJobs: number;
        };
        /**
         * JobResponse
         * @description POST /jobs, GET /jobs/{id} — 生成ジョブの状態。
         */
        JobResponse: {
            /** Jobid */
            jobId: string;
            /**
             * State
             * @description queued / running / done / failed / cancelled
             */
            state: string;
            /** Total */
            total: number;
            /** Finished */
            finished: number;
            /**
             * Queueposition
             * @description いま一緒に使っている、自分以外の子の数。0 なら独り占め
             */
            queuePosition: number;
            /** Error */
            error: string | null;
            /**
             * Results
             * @description できた行から順に増える
             */
            results: components["schemas"]["LineResultDTO"][];
        };
        /**
         * LineResultDTO
         * @description 1行ぶんの結果。成功なら artifactId、失敗なら error。
         */
        LineResultDTO: {
            /** Index */
            index: number;
            /** Artifactid */
            artifactId: string | null;
            /** Error */
            error: string | null;
        };
        /**
         * OpsResponse
         * @description GET /ops — 運用者（先生・TA）が見る状態。
         */
        OpsResponse: {
            /** Version */
            version: string;
            /** Serverid */
            serverId: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            warmup: components["schemas"]["WarmupDTO"];
            tts: components["schemas"]["TtsDTO"];
            queue: components["schemas"]["QueueDTO"];
            voices: components["schemas"]["VoicesDTO"];
            render: components["schemas"]["RenderDTO"];
            retention: components["schemas"]["RetentionDTO"];
            auth: components["schemas"]["AuthDTO"];
        };
        /** QueueDTO */
        QueueDTO: {
            /** Depth */
            depth: number;
            /** Activejobs */
            activeJobs: number;
        };
        /** RemovedResponse */
        RemovedResponse: {
            /** Removed */
            removed: boolean;
        };
        /** RenderDTO */
        RenderDTO: {
            /** Available */
            available: boolean;
            /** Reason */
            reason: string | null;
            /** Frontendorigin */
            frontendOrigin: string | null;
        };
        /** RenderRequest */
        RenderRequest: {
            /** Segments */
            segments: components["schemas"]["SegmentDTO"][];
        };
        /** RetentionDTO */
        RetentionDTO: {
            /** Artifactttlsec */
            artifactTtlSec: number;
            /** Videottlsec */
            videoTtlSec: number;
            /** Voicettlsec */
            voiceTtlSec: number;
        };
        /** RootResponse */
        RootResponse: {
            /** App */
            app: string;
            /** See */
            see: string;
        };
        /** SegmentDTO */
        SegmentDTO: {
            /** Startms */
            startMs: number;
            /** Durms */
            durMs: number;
            /** Panelpath */
            panelPath?: string | null;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /** Artifactid */
            artifactId?: string | null;
        };
        /** TtsDTO */
        TtsDTO: {
            /** Configured */
            configured: string;
            /** Effective */
            effective: string;
            /** Fallbackreason */
            fallbackReason: string | null;
            /** Workers */
            workers: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VoiceResponse
         * @description POST /voices — 参照音声を1回だけ預けた結果。
         */
        VoiceResponse: {
            /** Voiceid */
            voiceId: string;
            /** Expiressec */
            expiresSec: number;
        };
        /** VoicesDTO */
        VoicesDTO: {
            /** Enrolled */
            enrolled: number;
            /** Ttlsec */
            ttlSec: number;
        };
        /** WarmupDTO */
        WarmupDTO: {
            /** State */
            state: string;
            /** Error */
            error: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    enroll_voice_voices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_enroll_voice_voices_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceResponse"];
                };
            };
            /** @description 入力が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 大きすぎる */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_voice_voices__voice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemovedResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description 入力が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description いまの状態では実行できない（声の期限切れ・音声の欠落） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 見つからない（期限切れを含む） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 音声（wav）または動画（mp4 / webm） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": unknown;
                    "video/mp4": unknown;
                    "video/webm": unknown;
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 見つからない（期限切れを含む） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_artifact_artifacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_artifact_artifacts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description 入力が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 大きすぎる */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_video_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description 入力が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description いまの状態では実行できない（声の期限切れ・音声の欠落） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description この環境では利用できない（クライアント側にフォールバックする） */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ops_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpsResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cleanup_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupResponse"];
                };
            };
            /** @description イベントの合言葉が違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
